import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getGlobalData, getGlobalMetaData } from "@/lib/data";
import Header from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: {
// 		template: "%s | Strapi",
// 		default: "Strapi",
// 	},
// 	description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
	const metadata = await getGlobalMetaData();

	return {
		title: metadata?.title || "",
		description: metadata?.description || "",
		openGraph: {
			images: metadata?.image || "",
		},
	};
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const globalData = await getGlobalData();

	return (
		<html lang="en">
			<body className={inter.className}>
				<Header data={globalData.header} />
				{children}
				<Footer data={globalData.footer} />
				<Toaster position="bottom-center" />
			</body>
		</html>
	);
}
